trigger:
  branches:
    include:
      - main

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HashiCorp.Terraform.TerraformCLI@0
  displayName: 'Install Terraform'
  inputs:
    command: 'install'

- task: HashiCorp.Terraform.TerraformCLI@0
  displayName: 'Init Terraform'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

- task:HashiCorp.Terraform.TerraformCLI@0
  displayName: 'Validate Terraform'
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

- task: HashiCorp.Terraform.TerraformCLI@0
  displayName: 'Plan Terraform'
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceNameAzureRM: '<AzureRM service connection name>'

- task: HashiCorp.Terraform.TerraformCLI@0
  displayName: 'Apply Terraform'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
