trigger:
  branches:
    include:
      - main

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.4.2'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Free Trial(99766108-3d5d-4929-95ce-f17bc0a2ecd3)'
    backendAzureRmResourceGroupName: 'backstage'
    backendAzureRmStorageAccountName: 'backstagerp'
    backendAzureRmContainerName: 'backstagecon'
    backendAzureRmKey: 'tf/terraform.tfstate'
    workingDirectory: Terraform

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: Terraform

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Free Trial(99766108-3d5d-4929-95ce-f17bc0a2ecd3)'
    workingDirectory: Terraform

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply- auto-approve'
    environmentServiceNameAzureRM: 'Free Trial(99766108-3d5d-4929-95ce-f17bc0a2ecd3)'
    workingDirectory: Terraform
