trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: Terraform
        displayName: Terraform
        continueOnError: false
        pool:
          vmImage: $(vmImage)
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'