apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: backstage
  ports:
    - name: http
      port: 3000
      targetPort: 80
