name: 'Build and Deploy'
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/ # Needed for auth
        
    - uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        allow-no-subscriptions: true
        
    - name: 'acr details'
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2       
          
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: './backstageal'
        file: ./backstageal/Dockerfile.dockerbuild
        push: true
        tags: backstagerp.azurecr.io      
